PackageName: "SolverParameters"
PackageOwner: "JuliaSmoothOptimizers"
PackageUUID: "d076d87d-d1f9-4ea3-a44b-64b4cdd1e470"
_src_path: "https://github.com/JuliaSmoothOptimizers/JSOBestieTemplate.jl"
_commit: "v0.13.0"
AddBreakage: true
AddBenchmark: false
AddBenchmarkCI: true
